create extension if not exists pgcrypto;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  business text not null default 'Automotive',
  title text not null,
  slug text not null unique,
  short_description text not null,
  full_description text not null,
  category text not null,
  car_model text not null,
  location text not null,
  year integer not null,
  cover_image text not null,
  gallery_images text[] not null default '{}',
  gallery_captions text[] not null default '{}',
  gallery_items jsonb not null default '[]'::jsonb,
  video_url text,
  uploaded_video text,
  featured boolean not null default false,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  behind_the_scenes text
);

create table if not exists public.inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  company text,
  brief text not null,
  created_at timestamptz not null default now(),
  notification_status text not null default 'pending',
  notification_attempts integer not null default 0,
  notification_last_attempt_at timestamptz,
  notification_sent_at timestamptz
);

create table if not exists public.inquiry_rate_limits (
  id bigint generated by default as identity primary key,
  client_key_hash text not null,
  attempted_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id text primary key,
  brand_name text not null,
  brand_mark text not null,
  brand_strapline text not null,
  contact_email text not null,
  contact_phone text not null,
  contact_city text not null,
  social_links jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.projects
add column if not exists gallery_captions text[] not null default '{}';

alter table public.projects
add column if not exists gallery_items jsonb not null default '[]'::jsonb;

alter table public.projects
add column if not exists business text not null default 'Automotive';

alter table public.inquiries
add column if not exists service_type text;

alter table public.inquiries
add column if not exists notification_status text not null default 'pending',
add column if not exists notification_attempts integer not null default 0,
add column if not exists notification_last_attempt_at timestamptz,
add column if not exists notification_sent_at timestamptz;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.projects'::regclass
      and conname = 'projects_gallery_shape_check'
  ) then
    alter table public.projects
      add constraint projects_gallery_shape_check
      check (
        case
          when jsonb_typeof(gallery_items) = 'array' then
            cardinality(gallery_images) = cardinality(gallery_captions)
            and cardinality(gallery_images) = jsonb_array_length(gallery_items)
          else false
        end
      ) not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.projects'::regclass
      and conname = 'projects_year_check'
  ) then
    alter table public.projects
      add constraint projects_year_check
      check (year between 1900 and 2100) not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.inquiries'::regclass
      and conname = 'inquiries_service_type_check'
  ) then
    alter table public.inquiries
      add constraint inquiries_service_type_check
      check (
        service_type is null
        or service_type in (
          'Commercial Shoot',
          'Social Content',
          'Event Coverage',
          'Brand Campaign',
          'Other'
        )
      ) not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.inquiries'::regclass
      and conname = 'inquiries_notification_status_check'
  ) then
    alter table public.inquiries
      add constraint inquiries_notification_status_check
      check (
        notification_status in ('pending', 'sent', 'failed', 'skipped')
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.inquiries'::regclass
      and conname = 'inquiries_notification_attempts_check'
  ) then
    alter table public.inquiries
      add constraint inquiries_notification_attempts_check
      check (notification_attempts >= 0);
  end if;
end;
$$;

create index if not exists inquiries_notification_retry_idx
on public.inquiries (notification_last_attempt_at, created_at)
where notification_status in ('pending', 'failed');

alter table public.projects enable row level security;
alter table public.inquiries enable row level security;
alter table public.inquiry_rate_limits enable row level security;
alter table public.site_settings enable row level security;

revoke all on table public.inquiry_rate_limits from anon, authenticated;
grant select, insert, delete on table public.inquiry_rate_limits to service_role;

create or replace function public.consume_inquiry_rate_limit(
  p_client_key_hash text,
  p_max_attempts integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  recent_attempts integer;
  safe_window_seconds integer := greatest(p_window_seconds, 1);
begin
  if p_client_key_hash is null or length(p_client_key_hash) <> 64 then
    return false;
  end if;

  if p_max_attempts < 1 then
    return false;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_client_key_hash, 0));

  delete from public.inquiry_rate_limits
  where attempted_at <
    now() - make_interval(secs => safe_window_seconds);

  select count(*)
  into recent_attempts
  from public.inquiry_rate_limits
  where client_key_hash = p_client_key_hash;

  if recent_attempts >= p_max_attempts then
    return false;
  end if;

  insert into public.inquiry_rate_limits (client_key_hash)
  values (p_client_key_hash);

  return true;
end;
$$;

revoke all on function public.consume_inquiry_rate_limit(text, integer, integer)
from public, anon, authenticated;
grant execute on function public.consume_inquiry_rate_limit(
  text,
  integer,
  integer
) to service_role;

create or replace function public.delete_expired_inquiries(
  p_retention_days integer
)
returns bigint
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  deleted_count bigint;
begin
  if p_retention_days < 30 or p_retention_days > 3650 then
    raise exception 'Retention days must be between 30 and 3650.';
  end if;

  with deleted as (
    delete from public.inquiries
    where created_at < now() - make_interval(days => p_retention_days)
    returning 1
  )
  select count(*)::bigint into deleted_count from deleted;

  return deleted_count;
end;
$$;

revoke all on function public.delete_expired_inquiries(integer)
from public, anon, authenticated;
grant execute on function public.delete_expired_inquiries(integer)
to service_role;

create or replace function public.claim_inquiry_notifications(
  p_batch_size integer default 20,
  p_max_attempts integer default 5
)
returns table (
  inquiry_id uuid,
  name text,
  email text,
  company text,
  service_type text,
  brief text,
  notification_attempts integer
)
language plpgsql
volatile
security definer
set search_path = public
as $$
begin
  if p_batch_size < 1 or p_batch_size > 100 then
    raise exception 'Batch size must be between 1 and 100.';
  end if;

  if p_max_attempts < 1 or p_max_attempts > 20 then
    raise exception 'Maximum attempts must be between 1 and 20.';
  end if;

  return query
  with candidates as (
    select i.id
    from public.inquiries as i
    where i.notification_status in ('pending', 'failed')
      and i.notification_attempts < p_max_attempts
      and (
        i.notification_last_attempt_at is null
        or i.notification_last_attempt_at < now() - interval '5 minutes'
      )
    order by i.created_at
    for update skip locked
    limit p_batch_size
  )
  update public.inquiries as i
  set
    notification_status = 'pending',
    notification_attempts = i.notification_attempts + 1,
    notification_last_attempt_at = now()
  from candidates
  where i.id = candidates.id
  returning
    i.id,
    i.name,
    i.email,
    i.company,
    i.service_type,
    i.brief,
    i.notification_attempts;
end;
$$;

revoke all on function public.claim_inquiry_notifications(integer, integer)
from public, anon, authenticated;
grant execute on function public.claim_inquiry_notifications(integer, integer)
to service_role;

drop policy if exists "Public can read published projects" on public.projects;
create policy "Public can read published projects"
on public.projects
for select
using (published = true);

drop policy if exists "Authenticated users can manage projects" on public.projects;
drop policy if exists "Admins can manage projects" on public.projects;
create policy "Admins can manage projects"
on public.projects
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Anyone can create inquiries" on public.inquiries;
drop policy if exists "Authenticated users can read inquiries" on public.inquiries;
drop policy if exists "Admins can read inquiries" on public.inquiries;
create policy "Admins can read inquiries"
on public.inquiries
for select
to authenticated
using (public.is_admin());

-- Public inserts are intentionally disabled.
-- Inquiry submissions should go through the server route using the
-- SUPABASE_SERVICE_ROLE_KEY so spam protection and rate limiting can run
-- before data is written to the database.

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings"
on public.site_settings
for select
using (true);

drop policy if exists "Authenticated users can manage site settings" on public.site_settings;
drop policy if exists "Admins can manage site settings" on public.site_settings;
create policy "Admins can manage site settings"
on public.site_settings
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create index if not exists projects_created_at_idx on public.projects (created_at desc);
create index if not exists projects_published_created_at_idx
on public.projects (published, created_at desc);
create index if not exists inquiries_created_at_idx on public.inquiries (created_at desc);
create index if not exists inquiry_rate_limits_key_time_idx
on public.inquiry_rate_limits (client_key_hash, attempted_at desc);
create index if not exists inquiry_rate_limits_attempted_at_idx
on public.inquiry_rate_limits (attempted_at);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'projects',
  'projects',
  true,
  524288000,
  array[
    'image/avif',
    'image/gif',
    'image/jpeg',
    'image/png',
    'image/webp',
    'video/mp4',
    'video/quicktime',
    'video/webm'
  ]::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view project media" on storage.objects;
create policy "Public can view project media"
on storage.objects
for select
to public
using (bucket_id = 'projects');

drop policy if exists "Authenticated users can upload project media" on storage.objects;
drop policy if exists "Admins can upload project media" on storage.objects;
create policy "Admins can upload project media"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'projects' and public.is_admin());

drop policy if exists "Authenticated users can update project media" on storage.objects;
drop policy if exists "Admins can update project media" on storage.objects;
create policy "Admins can update project media"
on storage.objects
for update
to authenticated
using (bucket_id = 'projects' and public.is_admin())
with check (bucket_id = 'projects' and public.is_admin());

drop policy if exists "Authenticated users can delete project media" on storage.objects;
drop policy if exists "Admins can delete project media" on storage.objects;
create policy "Admins can delete project media"
on storage.objects
for delete
to authenticated
using (bucket_id = 'projects' and public.is_admin());

insert into public.site_settings (
  id,
  brand_name,
  brand_mark,
  brand_strapline,
  contact_email,
  contact_phone,
  contact_city,
  social_links
)
values (
  'global',
  'Lux Studio',
  'L/S',
  'Films and photography for car launches, dealer campaigns, and events.',
  'n.hagelberger@luxstudio.li',
  '',
  'Zurich / Milan / Monaco',
  '[{"label":"Instagram","href":"https://www.instagram.com/"}]'::jsonb
)
on conflict (id) do nothing;

-- ── Site settings: CMS content columns ─────────────────────────────────────
-- Run these once against an existing database. New installs get the columns
-- from the CREATE TABLE above after you add them there.

alter table public.site_settings
  add column if not exists seo_title        text,
  add column if not exists seo_description  text,
  add column if not exists hero_eyebrow     text,
  add column if not exists hero_headline_lead  text,
  add column if not exists hero_headline_trail text,
  add column if not exists hero_copy        text,
  add column if not exists hero_video_url   text,
  add column if not exists about_founder_note text,
  add column if not exists about_positioning  text,
  add column if not exists about_team_images  text[] not null default '{}',
  add column if not exists about_team_members jsonb not null default '[]'::jsonb,
  add column if not exists about_values     jsonb not null default '[]'::jsonb,
  add column if not exists services         jsonb not null default '[]'::jsonb,
  add column if not exists selected_frames  text[] not null default '{}',
  add column if not exists motion_frames    text[] not null default '{}',
  add column if not exists navigation_visibility jsonb not null default
    '{"home":true,"work":true,"services":true,"about":true,"contact":true}'::jsonb,
  add column if not exists site_copy jsonb not null default '{}'::jsonb;

alter table public.projects
  add column if not exists updated_at timestamptz not null default now();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

drop trigger if exists site_settings_set_updated_at on public.site_settings;
create trigger site_settings_set_updated_at
before update on public.site_settings
for each row execute function public.set_updated_at();

-- ── Inquiry email settings: admin-editable SMTP credentials ────────────────

create table if not exists public.email_settings (
  id text primary key default 'global',
  smtp_host text,
  smtp_port integer,
  smtp_secure boolean not null default false,
  smtp_user text,
  smtp_password text,
  inquiry_email_to text,
  inquiry_email_from text,
  verified_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.email_settings enable row level security;

-- Unlike site_settings, this table is never public-readable: only the
-- service-role-only /api/admin/email-settings route and the server-only
-- email sender read or write it.
--
-- verified_at is set only by a successful "send test email" from the admin
-- panel, and cleared on every save, so the panel can show "not working yet"
-- until the current configuration has actually been proven to send.
revoke all on table public.email_settings from anon, authenticated;
grant select, insert, update on table public.email_settings to service_role;

drop trigger if exists email_settings_set_updated_at on public.email_settings;
create trigger email_settings_set_updated_at
before update on public.email_settings
for each row execute function public.set_updated_at();

insert into public.email_settings (id)
values ('global')
on conflict (id) do nothing;

-- Storage setup:
-- 1. Bucket + object policies above assume the bucket id is `projects`.
-- 2. Store cover images in `covers/`, gallery stills in `gallery/`, and videos in `videos/`.
-- 3. If you want a different bucket id, adjust this SQL and NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET together.
