alter table public.projects
  alter column business set default 'Automotive';

update public.projects
set business = 'Automotive'
where lower(trim(business)) = 'car';

create table if not exists public.inquiry_rate_limits (
  id bigint generated by default as identity primary key,
  client_key_hash text not null,
  attempted_at timestamptz not null default now()
);

alter table public.inquiry_rate_limits enable row level security;

revoke all on table public.inquiry_rate_limits from anon, authenticated;
grant select, insert, delete on table public.inquiry_rate_limits to service_role;

create or replace function public.consume_inquiry_rate_limit(
  p_client_key_hash text,
  p_max_attempts integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  recent_attempts integer;
  safe_window_seconds integer := greatest(p_window_seconds, 1);
begin
  if p_client_key_hash is null or length(p_client_key_hash) <> 64 then
    return false;
  end if;

  if p_max_attempts < 1 then
    return false;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_client_key_hash, 0));

  delete from public.inquiry_rate_limits
  where attempted_at <
    now() - make_interval(secs => safe_window_seconds);

  select count(*)
  into recent_attempts
  from public.inquiry_rate_limits
  where client_key_hash = p_client_key_hash;

  if recent_attempts >= p_max_attempts then
    return false;
  end if;

  insert into public.inquiry_rate_limits (client_key_hash)
  values (p_client_key_hash);

  return true;
end;
$$;

revoke all on function public.consume_inquiry_rate_limit(
  text,
  integer,
  integer
) from public, anon, authenticated;
grant execute on function public.consume_inquiry_rate_limit(
  text,
  integer,
  integer
) to service_role;

create index if not exists inquiry_rate_limits_key_time_idx
on public.inquiry_rate_limits (client_key_hash, attempted_at desc);

create index if not exists inquiry_rate_limits_attempted_at_idx
on public.inquiry_rate_limits (attempted_at);

update public.site_settings
set contact_email = 'n.hagelberger@luxstudio.li'
where id = 'default';

notify pgrst, 'reload schema';
